# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../../puppet/manifests"
    puppet.module_path = "../../puppet/modules"
    puppet.manifest_file  = "site.pp"

    # puppet.options = "--verbose --debug"
  end
end
